# This file contains test data
# Change it based on you environment

lotus:
  codename: 'BLACK FLOWER'
  version: '0.8.5-SNAPSHOT'

mongo:
  username: kaikyu
  password: password
  ip: localhost
  db-name: test

logging:
  level: DEBUG
  format: '[%(levelname)-8s] - %(asctime)s - %(funcName)-20s @line %(lineno)-3s: %(message)s'
  date-format: '%H:%M:%S'
  file-name: resources/log.txt

startup:
  drop:
    dialogs: False
    triggers: False
    bots: False
    groups: False
    users: False

modules:
  classes:
    - modules.meteo.MeteoModule
    # - modules.trigger_helper.TriggerHelperModule
  meteo:
    enabled: True
  trigger-helper:
    enabled: True
    channel-id: -1001162520316
    msg-id: 12


defaults:
  language: IT
  maker:
    token: 777706082:AAGp1GeN56o6lVc6ahnMt9AbZSn9Cqxql10
    id: 777706082
  owner:
    id: 487353090
  retry-time: 5
  autom:
    min: 1
    max: 100

kitsu:
  backup-password: idk

meteo:
  appid: e296ee57588fc63608c11bfcf2858afa
